### ISSUE TITLE
Update for KSP version 1.5.1 and 1.6.1

### ISSUE THREAD

**Issue by Shivam60** [mwerle/DockingPortAlignmentIndicator#1]
Can we have an official recompiled version for KSP 1.5.1 and KSP 1.6.1?

**Comment by theonegalen** [comment]
Does it not work on those versions?

**Comment by mwerle** [comment]
Hi, sorry, I missed this issue.

I can't do official releases as I'm not the author as clearly stated on the front page.

But you can download my unofficial builds (just added for KSP 1.7.x although it -should- still work on older versions as well).
